/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MoviesMovieIdRouteImport } from './routes/movies.$movieId'
import { Route as MypageEditRouteImport } from './routes/mypage_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageEditRoute = MypageEditRouteImport.update({
  id: '/mypage_/edit',
  path: '/mypage/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/mypage/edit': typeof MypageEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/mypage/edit': typeof MypageEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/mypage_/edit': typeof MypageEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mypage'
    | '/search'
    | '/signup'
    | '/movies/$movieId'
    | '/mypage/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mypage'
    | '/search'
    | '/signup'
    | '/movies/$movieId'
    | '/mypage/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/mypage'
    | '/search'
    | '/signup'
    | '/movies/$movieId'
    | '/mypage_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MypageRoute: typeof MypageRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  MypageEditRoute: typeof MypageEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage_/edit': {
      id: '/mypage_/edit'
      path: '/mypage/edit'
      fullPath: '/mypage/edit'
      preLoaderRoute: typeof MypageEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MypageRoute: MypageRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  MypageEditRoute: MypageEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
